### ISSUE TITLE
sysl swagger generation cannot handle integer format

### ISSUE THREAD

**Issue by runnerdave** [anz-bank/sysl#460]
Please **do not post any internal, closed source snippets** on this public issue tracker!

### Expected behaviour

Sysl generation of go server code from swagger definition file including integer formats

### Actual behaviour

Multiple error without a clear message of what the problem is

### Steps to reproduce the behaviour

Try to generate go server code with a swagger definition that includes a format key for int32, for example:

````
parameters:
      - name: searchString
        type: integer
        required: true
        in: query
        format: int32
````

As an interim measure, by removing the format option the code generation works
