### ISSUE TITLE
Unstable OpenAPI 3 required fields

### ISSUE THREAD

**Issue by andrewemeryanz** [anz-bank/sysl#839]
### Description

Given the following type:
```
!type Address:
    line_1 <: string
    line_2 <: string
    line_3 <: string
    postcode <: string
```
Subsequent runs of `sysl export --format openapi3` produce a different ordering of the `required` fields:

```yaml
# first run
Address:
  ...
  required:
    - line_1
    - line_2
    - line_3
    - postcode

# second run
Address:
  ...
  required:
    - line_3
    - postcode
    - line_1
    - line_2
```

### Steps to Reproduce

1. Run `sysl export --format openapi3` multiple times.

**Expected behavior:**

Required fields are ordered in the order they appear within the `sysl` file.

**Actual behavior:**

Required fields are randomly ordered.

### Your Environments

```sh
$ sysl info
Build:
  Version      : 0.77.0
  Git Commit   : e78e0d0
  Date         : 2020-05-05T02:55:15Z
  Go Version   : go1.13.10 linux/amd64
  OS           : darwin/amd64
Runtime:
  GOOS/GOARCH  : darwin/amd64
  Go Version   : go1.13.10
```
