### ISSUE TITLE
Alphabetically ordered OpenAPI 3 properties

### ISSUE THREAD

**Issue by andrewemeryanz** [anz-bank/sysl#840]
### Description

Given the following type:
```
!type Address:
    line_1 <: string
    state <: string
    country <: string
    postcode <: string
```
The output of `sysl export --format openapi3` orders properties alphabetically:

```yaml
Address:
   properties:
     country:
       type: string
     line_1:
       type: string
     postcode:
       type: string
     state:
       type: string
```

While this behaviour isn't incorrect at the technical level, the exported file doesn't convey the same human relationship between fields.

### Steps to Reproduce

1. `sysl export --format openapi3`

**Expected behavior:**

Required fields are ordered in the order they appear within the `sysl` file:

```yaml
Address:
   properties:
     line_1:
       type: string
     line_1:
       type: string
     state:
       type: string
     country:
       type: string
     postcode:
       type: string
```

**Actual behavior:**

Required fields are ordered alphabetically.

### Your Environments

```sh
$ sysl info
Build:
  Version      : 0.77.0
  Git Commit   : e78e0d0
  Date         : 2020-05-05T02:55:15Z
  Go Version   : go1.13.10 linux/amd64
  OS           : darwin/amd64
Runtime:
  GOOS/GOARCH  : darwin/amd64
  Go Version   : go1.13.10
```
